spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/data-integrate?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      # MySQL 8.x以下: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 20
      min-idle: 1
      test-on-borrow: true
      initial-size: 1
      stat-view-servlet:
        login-username: root
        login-password: root
mybatis:
  type-aliases-package: com.it100000.eneity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
